---

- name: Add Remi repository
  yum_repository:
    name: remi
    description: Remi repository
    baseurl: "{{ remi_repo_url }}"
    gpgcheck: true
    gpgkey: "{{ remi_public_key_url }}"
    enabled: false

...
