---

- name: Add Remi repository
  yum_repository:
    name: remi
    description: Remi repository
    baseurl: "{{ repo_url }}"
    gpgcheck: true
    gpgkey: "{{ public_key_url }}"
    enabled: false
